default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %> 
  
development:
  <<: *default
  database: innovatron_dev
test:
  <<: *default
  database: innovatron_test

production:
  <<: *default
  database: innovatron_prod
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
